# Human readable title of application.
title: Sample Crossplane Stack
overviewShort: A short plaintext description
overview: A longer form plaintext description

# Markdown description of this entry
readme: |
 ## Sample Crossplane Stack

 This area would contain **markdown** describing this Stack, but this is *only* a Sample Stack.

# Version of project (optional)
# If omitted the version will be filled with the docker tag
# If set it must match the docker tag
version: 0.0.1

# Maintainer names and emails.
maintainers:
- name: Jared Watts
  email: jared@upbound.io

# Owner names and emails.
owners:
- name: Bassam Tabbara
  email: bassam@upbound.io

# Human readable company name.
company: Upbound

# Category that best describes this Stack
category: Sample

# Keywords that describe this application and help search indexing
keywords:
- "samples"
- "examples"
- "tutorials"

permissionScope: "Namespaced"
dependsOn: []

# Links to more information about the application (about page, source code, etc.)
website: "https://upbound.io"
source: "https://github.com/crossplaneio/sample-stack"

# License SPDX name: https://spdx.org/licenses/
license: Apache-2.0
